version: '3.7'
services:
  db:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "book"
    volumes: 
      - ./db-data:/var/lib/postgresql/data

  web:
    image: "aspnetcore_sample_web"
    container_name: web_asp
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

