apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-{{ .Release.Name}}
  namespace: default
  labels:
    app: web-{{ .Release.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-{{ .Release.Name}}
  strategy: {}
  template:
    metadata:
      labels:
        app: web-{{ .Release.Name}}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.pullPolicy}}
        name: web-{{ .Release.Name}}
        ports:
        - containerPort: 5000
        resources: {}
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 20
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
      terminationGracePeriodSeconds: 160
status: {}
